name: Build and Deploy WWW
on:
  push:
    branches:
      - master
jobs:
  Build-and-deploy:
    runs-on: ubuntu-20.04 # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    steps:
      - name: Update apt
        run: sudo apt-get update -y
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: bash ./build.sh
      - run: ls -al build
      - name: Deploy
        run: bash ./deploy.sh
        env:
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_SECRET_ACCESS_KEY }}

