name: Build and Deploy WWW
on:
  push:
    branches:
      - master
jobs:
  Build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Update apt
        run: sudo apt-get update -y
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - run: pwd
      - run: ls -al
      - name: Checkout
        uses: actions/checkout@master
      - run: ls -al
      - name: Build
        run: bash ./build.sh
      - run: ls -al
      - run: ls -al build
