name: Build and Deploy WWW
on: [push]
jobs:
  Build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Update apt
        run: sudo apt-get update -y
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
